STAGE.
SET SPEED TO  0.
SET ERR TO 0.
LOCK THROTTLE TO SPEED.
LOCK DIRECTION TO UP.
WAIT 5.
SET TARGETHEIGHT TO 10.
LOCK DIFF TO TARGETHEIGHT - ALT:RADAR.
SET P TO 0.1.
LOCK SPEED TO MAX(P*DIFF, 0).
UNTIL FALSE{
    PRINT DIFF.
    SET ERR TO ERR+DIFF.
}