SET SHIP TO CORE:VESSEL.
UNTIL FALSE
{
	CLEARSCREEN.
	PRINT "VERT SPEED: " + SHIP:VERTICALSPEED AT (2,2).
	PRINT "AIR  SPEED: " + SHIP:AIRSPEED	  AT (2,3).
	PRINT "GND  SPEED: " + SHIP:GROUNDSPEED   AT (2,4).

	PRINT "SHIP. : " + ARCCOS(SHIP:GROUNDSPEED / SHIP:AIRSPEED) AT (2,6).

	wait .5.
}

//vert speed CAN BE USED TO TRACK VERTICAL SPEED.
//ARCCOS GIVES |PITCH|

//WAYPOINTS CAN BE SELECTED WITH ALLWAYPOINTS(), AND THEN GRABBING THEIR GEOPOSITION AND CONVERTING TO A HEADING IS SUFFICIENT